// <auto-generated />
namespace GP.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class confmigrationdataannotation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confmigrationdataannotation));
        
        string IMigrationMetadata.Id
        {
            get { return "202012222329597_conf-migration-data-annotation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
